using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using System.Threading;

namespace WinFormImpl
{
    public partial class WinFormImpl : Form
    {
        private string m_Player1;
        private string m_Player2;

        public WinFormImpl()
        {
            m_Player1 = "";
            m_Player2 = "";
            InitializeComponent();
        }

        private void Play()
        {
            Thread.Sleep(200);
            if ((m_Player1.Length > 0) && (m_Player2.Length > 0))
            {
                if(
                // Intended error to demonstrate the error metrics generated by ct:
                // The correct next line should be:
                // (m_Player1 == "paper") should be: (m_Player1 != "paper")
                ((m_Player1 != "rock") && (m_Player1 != "scissors") && (m_Player1 == "paper")) ||
                ((m_Player2 != "rock") && (m_Player2 != "scissors") && (m_Player2 != "paper"))
                  )                
                    tbResults.Text = "Error: wrong input!";
                else if (m_Player1 == m_Player2)
                    tbResults.Text = "Tie";
                else if (
                    (m_Player1 == "paper" && m_Player2 == "rock") ||
                    (m_Player1 == "rock" && m_Player2 == "scissors") ||
                    (m_Player1 == "scissors" && m_Player2 == "paper"))
                    tbResults.Text = "Player1 wins";
                else
                    tbResults.Text = "Player2 wins";

                m_Player1 = "";
                m_Player2 = "";
            }
        }

        private void tbPlayer1_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                Submit1_Click(sender, e);
                tbPlayer2.Focus();
            } 
        }

        private void tbPlayer2_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                Submit2_Click(sender, e);
                tbPlayer1.Focus();
            } 
        }

        private void exitToolStripMenuItem_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void Submit1_Click(object sender, EventArgs e)
        {
            Thread.Sleep(200);
            m_Player1 = tbPlayer1.Text;
            tbPlayer1.Text = "";
            tbResults.Text = "";
            this.Play();
        }

        private void Submit2_Click(object sender, EventArgs e)
        {
            Thread.Sleep(200);
            m_Player2 = tbPlayer2.Text;
            tbPlayer2.Text = "";
            tbResults.Text = "";
            this.Play();
        }
    }
}